### ISSUE TITLE
This is awesome

### ISSUE THREAD

**Issue by neocybereth** [Alexloof/Next-GraphQL-Blog#1]
Did you learn this off any tutorials that you can recommend?

**Comment by Alexloof** [comment]
Hello @Sm00g15 ! 
I went through [HowToGraphQL](https://www.howtographql.com/) to learn the foundations. There were some lack of advanced techniques, so i was deep down in the Apollo docs for that. I also hade to experiment a lot to make it work. I hope you can take inspiration from my project so you can save some time. :-)
